kubernetesClusterDomain: cluster.local
nginx:
  nginx:
    image:
      repository: nginx
      tag: alpine
    resources:
      limits:
        cpu: 250m
        memory: 300Mi
      requests:
        cpu: 120m
        memory: 200Mi
  phpfpm:
    image:
      repository: php
      tag: fpm
    resources:
      limits:
        cpu: 250m
        memory: 300Mi
      requests:
        cpu: 120m
        memory: 200Mi
  replicas: 1
nginxConfig:
  nginxConf: |
    events {
    }
    http {
      include /etc/nginx/sites-enabled/*.*;
      include /etc/nginx/mime.types;
      server {
        listen 80 default_server;
        listen [::]:80 default_server;
        index index.php index.html;
        error_log  /var/log/nginx/app-error.log;
        access_log /var/log/nginx/app-access.log;
        root /var/www/nginx-php-app;
        location ~ \.php$ {
            try_files $uri =404;
            fastcgi_split_path_info ^(.+\.php)(/.+)$;
            fastcgi_pass 127.0.0.1:9000;
            fastcgi_index index.php;
            include fastcgi_params;
            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
            fastcgi_param PATH_INFO $fastcgi_path_info;
        }
        location / {
            try_files $uri $uri/ /index.php?$query_string;
            gzip_static on;
        }
      }
    }
nginxService:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  type: NodePort
phpfpm:
  ports:
  - name: listener
    port: 9000
    protocol: TCP
    targetPort: 9000
  type: NodePort
pvc:
  pvKarolisTask:
    storageRequest: 200Mi
