apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  labels:
    app: nginx
  {{- include "helm-nginx-php.labels" . | nindent 4 }}
spec:
  type: {{ .Values.nginxService.type }}
  selector:
    app: nginx
  {{- include "helm-nginx-php.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.nginxService.ports | toYaml | nindent 2 -}}