apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "helm-nginx-php.fullname" . }}-nginx-config
  labels:
  {{- include "helm-nginx-php.labels" . | nindent 4 }}
data:
  nginx.conf: {{ .Values.nginxConfig.nginxConf | quote }}