apiVersion: v1
kind: Service
metadata:
  name: {{ include "helm-nginx-php.fullname" . }}-phpfpm
  labels:
    app: phpfpm
  {{- include "helm-nginx-php.labels" . | nindent 4 }}
spec:
  type: {{ .Values.phpfpm.type }}
  selector:
    app: phpfpm
  {{- include "helm-nginx-php.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.phpfpm.ports | toYaml | nindent 2 -}}