apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "helm-nginx-php.fullname" . }}-pv-karolis-task
  labels:
  {{- include "helm-nginx-php.labels" . | nindent 4 }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.pvc.pvKarolisTask.storageRequest | quote }}