kind: Service
apiVersion: v1
metadata:
  name: phpfpm
  namespace: nginx-php
  labels:
    app: phpfpm
spec:
  ports:
    - name: listener
      protocol: TCP
      port: 9000
      targetPort: 9000
  selector:
    app: phpfpm
  type: NodePort